server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: -1
      max-request-size:  -1

# mybatis
mybatis:
  type-aliases-package: com.ratel.shiro.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
   level:
    com.ratel.shiro: debug


download:
    zipBasePath2: D:/temp/download/

renren:
  redis:
    open: false
  shiro:
    redis: false
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
    expire: 604800
    header: token




